### PR TITLE
feat: workdir control

### PR DESCRIPTION
**Pull request by ohaiibuzzle**
Allow users to control the working directory of a given application with the "smart" option of selecting the binary's directory (most of the time correct)

### CODE REVIEW

**Review by Marsgames — APPROVED** [review]

**Comment by alexsch01** [comment]
What happened to this pull request and the following?

https://github.com/IsaacMarovitz/Whisky/pull/109
https://github.com/IsaacMarovitz/Whisky/pull/110
https://github.com/IsaacMarovitz/Whisky/pull/113
https://github.com/IsaacMarovitz/Whisky/pull/114

(I may have missed a couple, these were closed and the changes are not in main branch as far as I can see)

**Comment by IsaacMarovitz** [comment]
> What happened to this pull request and the following? @IsaacMarovitz

I had to do a massive and messy force push to get rid of LFS data in the repo. As a result, GitHub closed all current PRs as the commit history technically got out of sync.

**Comment by alexsch01** [comment]
Ok, dang. Yeah the PRs I listed above should be about it for those affected

**Comment by IsaacMarovitz** [comment]
> Ok, dang. Yeah the PRs I listed above should be about it for those affected

Fixed up/merged #27, #113, and #114

**Comment by JoshuaBrest** [comment]
> > What happened to this pull request and the following? @IsaacMarovitz
> 
> I had to do a massive and messy force push to get rid of LFS data in the repo. As a result, GitHub closed all current PRs as the commit history technically got out of sync.

ahhhhh

**Pull request closed without merging**
