### PR TITLE
Adds loading indicator for a bottle

### PR DESCRIPTION
**Pull request by rhysm94**
I've added an indicator in the Bottle list to show when a new bottle is being loaded.
It always appears above the list, so as to not potentially overlap bottles if enough are created.
I looked into placing it in the detail view, but that didn't appear? 🤷🏻‍♂️ Just SwiftUI things.
Probably makes the most sense in the Bottle list anyway.

https://github.com/IsaacMarovitz/Whisky/assets/11096937/2e064cc8-6a4b-4d69-a6c8-6efa47d3b118

### CODE REVIEW

**Comment by Frityet** [comment]
Thank you so much!!! I was really annoyed at this too

**Review by Frityet — APPROVED** [review]

**Review by l3gacyb3ta — APPROVED** [review]

**Comment by l3gacyb3ta** [comment]
Looks good to me!

**Review by Marsgames — APPROVED** [review]

**Comment by IsaacMarovitz** [comment]
Personally, I'd kinda prefer if it appeared at the bottom of the list as that's kinda more standard to how Mac apps usually show this kind of thing. Either that or as an entry in the List grayed out with the progress bar next to it.

**Comment by rhysm94** [comment]
> Personally, I'd kinda prefer if it appeared at the bottom of the list as that's kinda more standard to how Mac apps usually show this kind of thing. Either that or as an entry in the List grayed out with the progress bar next to it.

Cool, I'll move it to the bottom of the list, and attempt to scroll to it.
I was aiming for something like the pull-to-refresh style activity indicator, but happy to move it!

**Comment by JoshuaBrest** [comment]
I think it should be a sheet with one of those inditerminate progress bars

**Pull request closed without merging**
