### PR TITLE
macOS 13.3 support

### LINKED ISSUE #29: macOS 13.4 support
game-porting-toolkit works flawlessly on macOS 13.3, just requiring the "Command line tools for XCode 15 beta". Whilst working on my pull request (#13), I backported it to macOS 13 to work on my machine, with the only change being the closure arguments for a SwiftUI view. Should I make a PR to introduce this change?

### PR DESCRIPTION
**Pull request by Frityet**
Fixes #29, unsure if it still works on macOS 14

### CODE REVIEW

**Comment by Frityet** [comment]
Confirmed to build on macOS 14 🥳

**Review by Marsgames — APPROVED** [review]

**Review by IsaacMarovitz — APPROVED** [review]

**Review by RyzenDew — APPROVED** [review]
Looks great and it works thanks!

**Comment by pklebba** [comment]
I suggest changing FAQ in readme as still says that Sonoma is required.

**Comment by RyzenDew** [comment]
> I suggest changing FAQ in readme as still says that Sonoma is required.

i will change it if his get's merged first

**Comment by kklem0** [comment]
Is there a "nightly" dmg that I could download?

**Pull request merged**
